import express from 'express';
import { body } from 'express-validator';
import { protect } from '../middleware/auth.js';
import { trainerOnly } from '../middleware/role.js';
import { validate } from '../middleware/validate.js';
import { uploadImage, verifyUploadedImage } from '../middleware/upload.js';
import { createMaterial, deleteMaterial, downloadTrainerCertificate, getTrainerCertificates, getTrainerDashboard, updateMaterial, updateTrainerProfile } from '../controllers/trainerApplication.controller.js';
import { idParam, trainerProfileValidation, validateObjectIdParam } from '../middleware/validationRules.js';

const router = express.Router();
['id', 'trainingId', 'materialId'].forEach((name) => router.param(name, validateObjectIdParam));
router.use(protect, trainerOnly);
router.get('/dashboard', getTrainerDashboard);
router.get('/certificates', getTrainerCertificates);
router.get('/certificates/:id/download', idParam(), validate, downloadTrainerCertificate);
router.put('/profile', uploadImage.single('photo'), verifyUploadedImage, trainerProfileValidation, validate, updateTrainerProfile);
const materialValidation = [body('title').trim().notEmpty().isLength({ max: 150 }), body('url').isURL({ protocols: ['http', 'https'], require_protocol: true }), body('description').optional().trim().isLength({ max: 500 })];
router.post('/trainings/:trainingId/materials', idParam('trainingId', 'training ID'), materialValidation, validate, createMaterial);
router.put('/trainings/:trainingId/materials/:materialId', idParam('trainingId', 'training ID'), idParam('materialId', 'material ID'), materialValidation, validate, updateMaterial);
router.delete('/trainings/:trainingId/materials/:materialId', idParam('trainingId', 'training ID'), idParam('materialId', 'material ID'), validate, deleteMaterial);
export default router;
