import React, { useRef, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import api from '../../api/axios';
import toast from 'react-hot-toast';
import { CameraIcon, CheckIcon, EyeIcon, EyeSlashIcon, KeyIcon, PencilIcon, ShieldCheckIcon, XMarkIcon } from '@heroicons/react/24/outline';
import PhoneInput from '../../components/common/PhoneInput';

const photoUrl = (path) => path ? (path.startsWith('http') ? path : `/${path.replace(/^\//, '')}`) : null;

const ModeratorProfile = () => {
  const { user, updateProfile } = useAuth();
  const fileRef = useRef(null);
  const [editing, setEditing] = useState(false);
  const [photo, setPhoto] = useState(null);
  const [preview, setPreview] = useState(photoUrl(user?.profilePhoto));
  const [form, setForm] = useState({ fullName: user?.fullName || '', phone: user?.phone || '' });
  const [saving, setSaving] = useState(false);
  const [changingPassword, setChangingPassword] = useState(false);
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [visible, setVisible] = useState({ current: false, next: false, confirm: false });

  const selectPhoto = (event) => { const file = event.target.files?.[0]; if (!file) return; setPhoto(file); setPreview(URL.createObjectURL(file)); setEditing(true); };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const data = new FormData(); data.append('fullName', form.fullName); data.append('phone', form.phone); if (photo) data.append('profilePhoto', photo); const updated = await updateProfile(data); setPreview(photoUrl(updated?.profilePhoto)); setPhoto(null); setEditing(false); } finally { setSaving(false); } };
  const cancel = () => { setForm({ fullName: user?.fullName || '', phone: user?.phone || '' }); setPhoto(null); setPreview(photoUrl(user?.profilePhoto)); setEditing(false); };
  const changePassword = async (event) => { event.preventDefault(); if (passwords.newPassword !== passwords.confirmPassword) return toast.error('New passwords do not match.'); if (passwords.newPassword.length < 8) return toast.error('Password must be at least 8 characters.'); setSaving(true); try { const res = await api.put('/auth/change-password', { currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }); if (res.success) { toast.success('Password updated.'); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); setChangingPassword(false); } } catch (error) { toast.error(error.message || 'Password update failed.'); } finally { setSaving(false); } };
  const inputClass = 'w-full rounded-xl border border-slate-300 px-4 py-3 text-sm';

  return <div className="mx-auto max-w-5xl space-y-6"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-6 border-b border-slate-200 bg-slate-50/70 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div className="flex items-center gap-5"><div className="group relative flex h-24 w-24 items-center justify-center overflow-hidden rounded-full border-4 border-white bg-[#1a6b3c] text-3xl font-bold text-white shadow-md">{preview ? <img src={preview} alt={user?.fullName} className="h-full w-full object-cover" /> : (user?.fullName || 'M').charAt(0)}<button type="button" onClick={() => fileRef.current?.click()} className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 focus:opacity-100" aria-label="Update profile photo"><CameraIcon className="h-7 w-7" /></button></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={selectPhoto} /><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1a6b3c]">Moderator profile</p><h1 className="mt-1 text-2xl font-bold text-slate-950">{user?.fullName}</h1><p className="mt-1 text-sm text-slate-500">{user?.email}</p></div></div>{editing ? <button onClick={cancel} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 text-sm font-semibold"><XMarkIcon className="h-4 w-4" /> Cancel</button> : <button onClick={() => setEditing(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#1a6b3c] px-5 text-sm font-semibold text-white"><PencilIcon className="h-4 w-4" /> Edit profile</button>}</div>
    {editing ? <form onSubmit={save} className="grid grid-cols-1 gap-5 p-6 sm:grid-cols-2 sm:p-8"><label>Full name<input value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} className={`${inputClass} mt-2`} required /></label><label>Email address<input value={user?.email || ''} className={`${inputClass} mt-2 bg-slate-100 text-slate-500`} disabled /></label><label>Phone number<PhoneInput className="mt-2" value={form.phone} onChange={(phone) => setForm({ ...form, phone })} /></label><div className="flex items-end"><button disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#1a6b3c] px-6 text-sm font-bold text-white"><CheckIcon className="h-5 w-5" />{saving ? 'Saving…' : 'Save profile'}</button></div></form> : <div className="grid grid-cols-1 gap-px bg-slate-200 sm:grid-cols-3">{[['Full name', user?.fullName], ['Email address', user?.email], ['Phone number', user?.phone || 'Not provided']].map(([label, value]) => <div key={label} className="bg-white p-6"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-sm font-semibold text-slate-800">{value}</p></div>)}</div>}
    </section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-[#1a6b3c]"><ShieldCheckIcon className="h-6 w-6" /></span><div><h2 className="font-bold text-slate-950">Password & security</h2><p className="mt-1 text-sm text-slate-500">Protect access to session operations.</p></div></div>{!changingPassword && <button onClick={() => setChangingPassword(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 text-sm font-semibold"><KeyIcon className="h-5 w-5" /> Change password</button>}</div>{changingPassword && <form onSubmit={changePassword} className="mt-7 grid grid-cols-1 gap-5 border-t border-slate-100 pt-7 lg:grid-cols-3">{[['currentPassword', 'Current password', 'current', 'Enter current password'], ['newPassword', 'New password', 'next', 'At least 8 characters'], ['confirmPassword', 'Confirm password', 'confirm', 'Re-enter new password']].map(([key, label, flag, placeholder]) => <label key={key}>{label}<div className="relative mt-2"><input type={visible[flag] ? 'text' : 'password'} value={passwords[key]} onChange={(e) => setPasswords({ ...passwords, [key]: e.target.value })} placeholder={placeholder} className={`${inputClass} pr-12`} required /><button type="button" onClick={() => setVisible({ ...visible, [flag]: !visible[flag] })} className="absolute inset-y-0 right-0 flex w-11 items-center justify-center text-slate-400">{visible[flag] ? <EyeSlashIcon className="h-5 w-5" /> : <EyeIcon className="h-5 w-5" />}</button></div></label>)}<div className="flex gap-3 lg:col-span-3"><button disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white">Update password</button><button type="button" onClick={() => setChangingPassword(false)} className="rounded-xl px-5 text-sm font-semibold text-slate-600">Cancel</button></div></form>}</section></div>;
};

export default ModeratorProfile;
