import React, { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeftIcon, ChatBubbleLeftRightIcon, StarIcon } from '@heroicons/react/24/outline';
import api from '../../api/axios';
import { formatTimeRange12 } from '../../utils/timeFormat';

export default function TrainerFeedbackDetails() {
  const { trainingId } = useParams();
  const [session, setSession] = useState(undefined);
  useEffect(() => { api.get('/trainer/dashboard').then((response) => setSession((response.data.sessions || []).find((item) => item._id === trainingId) || null)).catch((error) => { toast.error(error.message || 'Unable to load session feedback.'); setSession(null); }); }, [trainingId]);
  const average = useMemo(() => { const ratings = session?.feedback.map((item) => item.trainerRating).filter(Number.isFinite) || []; return ratings.length ? (ratings.reduce((sum, rating) => sum + rating, 0) / ratings.length).toFixed(1) : '—'; }, [session]);
  if (session === undefined) return <div className="h-72 animate-pulse rounded-2xl bg-slate-200" />;
  if (!session) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><h1 className="font-bold">Session not found</h1><Link to="/trainer/feedback" className="mt-4 inline-flex text-sm font-bold text-[#1a6b3c]">Return to feedback</Link></div>;
  return <div className="space-y-6"><header><Link to="/trainer/feedback" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[#1a6b3c]"><ArrowLeftIcon className="h-4 w-4" /> Back to feedback sessions</Link><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#1a6b3c]">Session feedback</p><h1 className="mt-1 text-2xl font-black text-slate-950 sm:text-3xl">{session.title}</h1><p className="mt-2 text-sm text-slate-500">{new Date(session.date).toLocaleDateString()} · {formatTimeRange12(session.startTime, session.endTime)}</p></div><div className="flex gap-2"><Metric label="Responses" value={session.feedback.length} /><Metric label="Average" value={`${average}/5`} /></div></div></header>{session.feedback.length ? <section aria-label="All participant feedback" className="grid gap-4 lg:grid-cols-2">{session.feedback.map((item, index) => <FeedbackMessage key={item._id} item={item} number={index + 1} />)}</section> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><ChatBubbleLeftRightIcon className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">No feedback received for this session yet.</p></div>}</div>;
}
function Metric({ label, value }) { return <div className="min-w-24 rounded-xl border border-slate-200 bg-white px-4 py-2 text-center shadow-sm"><p className="text-lg font-black text-slate-950">{value}</p><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p></div>; }
function FeedbackMessage({ item, number }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">Response {number}</span><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-[#1a6b3c]"><StarIcon className="h-4 w-4" /> {item.trainerRating}/5</span></div><p className="mt-4 text-sm leading-6 text-slate-700">{item.comments || 'No written comment was provided.'}</p>{item.suggestions && <div className="mt-4 border-t border-slate-100 pt-4"><p className="text-xs font-bold text-slate-500">Suggestion</p><p className="mt-1 text-sm leading-6 text-slate-600">{item.suggestions}</p></div>}</article>; }
