import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { AcademicCapIcon, CalendarDaysIcon, ChatBubbleLeftRightIcon, ClockIcon, DocumentTextIcon, MapPinIcon, UserGroupIcon, VideoCameraIcon } from '@heroicons/react/24/outline';
import api from '../../api/axios';
import { formatTimeRange12 } from '../../utils/timeFormat';

const sessionTime = (session) => new Date(`${String(session.date).slice(0, 10)}T${session.startTime || '00:00'}:00+03:00`).getTime();
const sessionEndTime = (session) => new Date(`${String(session.date).slice(0, 10)}T${session.endTime || '23:59'}:00+03:00`).getTime();
const countdown = (milliseconds) => { const seconds = Math.max(0, Math.ceil(milliseconds / 1000)); return `${Math.floor(seconds / 3600)}h ${String(Math.floor((seconds % 3600) / 60)).padStart(2, '0')}m ${String(seconds % 60).padStart(2, '0')}s`; };
const statusStyle = { ongoing: 'bg-green-100 text-green-800', completed: 'bg-black/5 text-black/60', registration_open: 'bg-green-50 text-green-800', published: 'bg-green-50 text-green-800', draft: 'bg-black/5 text-black/60', cancelled: 'bg-red-50 text-red-700' };

export default function TrainerDashboard({ sessionsOnly = false }) {
  const [data, setData] = useState(null);
  const [now, setNow] = useState(Date.now());
  const load = async () => { try { const response = await api.get('/trainer/dashboard'); setData(response.data); } catch (error) { toast.error(error.message || 'Unable to load trainer workspace.'); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);

  const summary = useMemo(() => {
    const sessions = data?.sessions || [];
    const now = Date.now();
    const upcoming = sessions.filter((item) => sessionEndTime(item) >= now && !['cancelled', 'completed'].includes(item.status)).sort((a, b) => sessionTime(a) - sessionTime(b));
    const participants = sessions.reduce((total, item) => total + item.participants.length, 0);
    const present = sessions.reduce((total, item) => total + item.attendancePresent, 0);
    const ratings = sessions.flatMap((item) => item.feedback.map((feedback) => feedback.trainerRating)).filter(Number.isFinite);
    return { upcoming, participants, present, attendanceRate: participants ? Math.round((present / participants) * 100) : 0, averageRating: ratings.length ? (ratings.reduce((sum, rating) => sum + rating, 0) / ratings.length).toFixed(1) : '—', feedbackCount: ratings.length };
  }, [data]);

  if (!data) return <DashboardSkeleton />;
  const nextSession = summary.upcoming[0];
  return <div className="space-y-7">
    <header className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#1a6b3c]">{sessionsOnly ? 'Session workspace' : 'Trainer dashboard'}</p><h1 className="mt-1 text-2xl font-black text-slate-950 sm:text-3xl">{sessionsOnly ? 'My sessions' : `Welcome, ${data.trainer.name?.split(' ')[0]}`}</h1><p className="mt-2 text-sm text-slate-500">{sessionsOnly ? 'Review feedback and share learning materials for each assigned session.' : 'A clear overview of your training activity and performance.'}</p></div>{!sessionsOnly && <span className="w-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-[#1a6b3c]">Approved trainer</span>}</header>

    {!sessionsOnly && <><section className="grid grid-cols-2 gap-3 xl:grid-cols-4" aria-label="Trainer analytics">
      <Metric icon={AcademicCapIcon} label="Assigned sessions" value={data.sessions.length} detail={`${summary.upcoming.length} upcoming`} />
      <Metric icon={UserGroupIcon} label="Approved learners" value={summary.participants} detail="Across your sessions" />
      <Metric icon={CalendarDaysIcon} label="Attendance rate" value={`${summary.attendanceRate}%`} detail={`${summary.present} marked present`} />
      <Metric icon={ChatBubbleLeftRightIcon} label="Trainer rating" value={summary.averageRating === '—' ? '—' : `${summary.averageRating}/5`} detail={`${summary.feedbackCount} responses`} />
    </section>

    <section className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]">
      <div className="relative overflow-hidden rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><span className="absolute inset-y-0 left-0 w-1.5 bg-[#1a6b3c]" /><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1a6b3c]">Next session</p>{nextSession ? <div className="mt-4"><h2 className="text-2xl font-bold text-slate-950">{nextSession.title}</h2><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span className="inline-flex items-center gap-2"><CalendarDaysIcon className="h-5 w-5 text-[#1a6b3c]" />{new Date(nextSession.date).toLocaleDateString()}</span><span className="inline-flex items-center gap-2"><ClockIcon className="h-5 w-5 text-[#1a6b3c]" />{formatTimeRange12(nextSession.startTime, nextSession.endTime)}</span><span className="inline-flex items-center gap-2"><MapPinIcon className="h-5 w-5 text-[#1a6b3c]" />Day {nextSession.eventDay?.dayNumber || '—'}</span></div>{nextSession.meeting ? sessionTime(nextSession) > now ? <button type="button" disabled className="mt-5 inline-flex cursor-not-allowed items-center gap-2 rounded-xl bg-slate-200 px-5 py-3 text-sm font-bold text-slate-500"><VideoCameraIcon className="h-5 w-5" /> Join available in {countdown(sessionTime(nextSession) - now)}</button> : <a href={nextSession.meeting.meetingUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#1da156] px-5 py-3 text-sm font-bold text-white"><VideoCameraIcon className="h-5 w-5" /> Join meeting</a> : <p className="mt-5 text-sm text-slate-500">Meeting access has not been added by the administrator.</p>}</div> : <p className="mt-4 text-sm text-slate-500">No upcoming session is currently assigned.</p>}</div>
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Workspace summary</p><dl className="mt-4 space-y-4"><SummaryRow label="Learning materials" value={data.sessions.reduce((sum, item) => sum + item.materials.length, 0)} /><SummaryRow label="Completed sessions" value={data.sessions.filter((item) => item.status === 'completed').length} /><SummaryRow label="Feedback comments" value={data.sessions.reduce((sum, item) => sum + item.feedback.filter((feedback) => feedback.comments).length, 0)} /></dl></div>
    </section></>}

    {sessionsOnly && <section>{data.sessions.length ? <div className="space-y-4">{data.sessions.map((session) => <SessionSummaryCard key={session._id} session={session} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><AcademicCapIcon className="mx-auto h-10 w-10 text-slate-300" /><h3 className="mt-3 font-bold text-slate-900">No assigned sessions</h3><p className="mt-1 text-sm text-slate-500">Sessions will appear here after an administrator assigns you.</p></div>}</section>}
  </div>;
}

function Metric({ icon: Icon, label, value, detail }) { return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-green-50 text-[#1a6b3c]"><Icon className="h-5 w-5" /></span><p className="mt-4 text-2xl font-black text-slate-950">{value}</p><p className="text-xs font-bold text-slate-700 sm:text-sm">{label}</p><p className="mt-1 text-[11px] text-slate-400 sm:text-xs">{detail}</p></article>; }
function SummaryRow({ label, value }) { return <div className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 last:pb-0"><dt className="text-sm text-slate-500">{label}</dt><dd className="font-black text-slate-950">{value}</dd></div>; }

function SessionSummaryCard({ session }) {
  const attendanceRate = session.participants.length ? Math.round((session.attendancePresent / session.participants.length) * 100) : 0;
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold uppercase ${statusStyle[session.status] || 'bg-slate-100 text-slate-600'}`}>{session.status.replaceAll('_', ' ')}</span><span className="text-xs text-slate-400">{session.category?.name || 'Uncategorized'}</span></div><h2 className="mt-2 text-lg font-bold text-slate-950">{session.title}</h2><p className="mt-1 text-sm text-slate-500">{new Date(session.date).toLocaleDateString()} · {formatTimeRange12(session.startTime, session.endTime)} · Day {session.eventDay?.dayNumber || '—'}</p><p className="mt-2 text-xs text-slate-400">{session.participants.length} learners · {attendanceRate}% attendance</p></div><div className="flex shrink-0 flex-wrap gap-2"><Link to="/trainer/feedback" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-700 hover:bg-slate-50"><ChatBubbleLeftRightIcon className="h-5 w-5 text-[#1a6b3c]" /> View feedback</Link><Link to="/trainer/materials" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#1a6b3c] px-4 text-sm font-bold text-white hover:bg-[#124d2a]"><DocumentTextIcon className="h-5 w-5" /> Manage materials</Link></div></div></article>;
}

/* Superseded by the dedicated materials and feedback pages.
function SessionCard({ session, onAdd, onRemove, onUpload, onDownload }) {
  const attendanceRate = session.participants.length ? Math.round((session.attendancePresent / session.participants.length) * 100) : 0;
  const editable = session.status !== 'cancelled';

  return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <header className="flex items-start justify-between gap-4 p-5 sm:p-6">
      <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold uppercase ${statusStyle[session.status] || 'bg-slate-100 text-slate-600'}`}>{session.status.replaceAll('_', ' ')}</span><span className="text-xs text-slate-400">{session.category?.name || 'Uncategorized'}</span></div><h3 className="mt-2 text-lg font-bold text-slate-950">{session.title}</h3><p className="mt-2 text-sm text-slate-500">{new Date(session.date).toLocaleDateString()} · {formatTimeRange12(session.startTime, session.endTime)} · Day {session.eventDay?.dayNumber || '—'}</p></div>
      <div className="hidden shrink-0 text-right text-xs sm:block"><p className="font-bold text-slate-900">{session.participants.length} learners</p><p className="mt-1 text-slate-400">{attendanceRate}% attendance</p></div>
    </header>

    <div className="border-t border-slate-100 bg-slate-50/60 p-4 sm:p-5"><div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]">
      <Panel title="Participant feedback" icon={ChatBubbleLeftRightIcon}>{session.feedback.length ? <div className="space-y-2">{session.feedback.map((item) => <div key={item._id} className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><p className="font-bold text-[#1a6b3c]">{item.trainerRating}/5 rating</p>{item.comments && <p className="mt-1 leading-6 text-slate-600">{item.comments}</p>}</div>)}</div> : <Empty text="No feedback received yet." />}</Panel>

      <Panel title="Learning materials" icon={DocumentTextIcon}>
        <div className="space-y-2">{session.materials.map((item) => <MaterialRow key={item._id} item={item} editable={editable} onDownload={onDownload} onRemove={() => onRemove(session._id, item._id)} />)}{!session.materials.length && <Empty text="No materials yet. Add a useful link or upload a file below." />}</div>
        {editable && <div className="mt-4 grid gap-3 lg:grid-cols-2">
          <form onSubmit={(event) => onAdd(event, session._id)} className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-3"><FormHeading icon={LinkIcon} title="Add link" text="Share an external resource." /><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1"><Field label="Title" name="title" placeholder="Presentation slides" required /><Field label="URL" name="url" type="url" placeholder="https://docs.google.com/..." required /></div><button className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#1a6b3c] px-4 text-sm font-bold text-white shadow-sm transition hover:bg-[#124d2a] focus:outline-none focus:ring-2 focus:ring-[#1a6b3c] focus:ring-offset-2"><LinkIcon className="h-4 w-4" /> Add link</button></form>
          <UploadForm sessionId={session._id} onUpload={onUpload} />
        </div>}
      </Panel>
    </div></div>
  </article>;
}

function MaterialRow({ item, editable, onDownload, onRemove }) { return <div className="group flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-emerald-50 text-[#1a6b3c]">{item.file?.path ? <DocumentTextIcon className="h-5 w-5" /> : <LinkIcon className="h-5 w-5" />}</span>{item.file?.path ? <button type="button" onClick={() => onDownload(item)} className="min-w-0 text-left"><span className="block truncate text-sm font-bold text-slate-900 group-hover:text-[#1a6b3c]">{item.title}</span><span className="mt-0.5 flex items-center gap-1 text-xs text-slate-500"><ArrowDownTrayIcon className="h-3.5 w-3.5" /> Download file</span></button> : <a href={item.url} target="_blank" rel="noreferrer" className="min-w-0"><span className="block truncate text-sm font-bold text-slate-900 group-hover:text-[#1a6b3c]">{item.title}</span><span className="mt-0.5 flex items-center gap-1 text-xs text-slate-500"><ArrowTopRightOnSquareIcon className="h-3.5 w-3.5" /> Open link</span></a>}</div>{editable && <button type="button" onClick={onRemove} aria-label={`Delete ${item.title}`} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-slate-400 transition hover:bg-red-50 hover:text-red-600 focus:outline-none focus:ring-2 focus:ring-red-500"><TrashIcon className="h-5 w-5" /></button>}</div>; }
function UploadForm({ sessionId, onUpload }) {
  const [fileName, setFileName] = useState('');
  const submit = async (event) => { await onUpload(event, sessionId); setFileName(''); };
  return <form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-3"><FormHeading icon={CloudArrowUpIcon} title="Upload file" text="PDF, Office, text, or ZIP." /><Field label="Display name (optional)" name="title" placeholder="Defaults to file name" /><label className="mt-2 flex min-h-16 cursor-pointer items-center gap-3 rounded-xl border border-dashed border-emerald-300 bg-emerald-50/40 px-3 transition hover:border-[#1a6b3c] hover:bg-emerald-50 focus-within:ring-2 focus-within:ring-[#1a6b3c] focus-within:ring-offset-2"><input name="file" type="file" required accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.txt,.zip" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-white text-[#1a6b3c] shadow-sm"><CloudArrowUpIcon className="h-6 w-6" /></span><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-800">{fileName || 'Choose a file'}</span><span className="block text-xs text-slate-500">Click to browse your device</span></span></label><button className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#1a6b3c] bg-white px-4 text-sm font-bold text-[#1a6b3c] transition hover:bg-emerald-50 focus:outline-none focus:ring-2 focus:ring-[#1a6b3c] focus:ring-offset-2"><CloudArrowUpIcon className="h-5 w-5" /> Upload selected file</button></form>;
}
function FormHeading({ icon: Icon, title, text }) { return <div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-white text-[#1a6b3c] shadow-sm"><Icon className="h-5 w-5" /></span><div><h5 className="text-sm font-bold text-slate-900">{title}</h5><p className="text-xs text-slate-500">{text}</p></div></div>; }
function Field({ label, ...props }) { return <label className="block text-xs font-bold text-slate-700">{label}<input {...props} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none transition focus:border-[#1a6b3c] focus:ring-2 focus:ring-emerald-100" /></label>; }
*/

/* Previous accordion retained temporarily for an easy visual rollback.
function LegacySessionCard({ session, open, onToggle, onAdd, onRemove, onUpload, onDownload }) {
  const attendanceRate = session.participants.length ? Math.round((session.attendancePresent / session.participants.length) * 100) : 0;
  return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={onToggle} className="flex w-full items-start justify-between gap-4 p-5 text-left sm:p-6" aria-expanded={open}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold uppercase ${statusStyle[session.status] || 'bg-slate-100 text-slate-600'}`}>{session.status.replaceAll('_', ' ')}</span><span className="text-xs text-slate-400">{session.category?.name || 'Uncategorized'}</span></div><h3 className="mt-2 text-lg font-bold text-slate-950">{session.title}</h3><p className="mt-2 text-sm text-slate-500">{new Date(session.date).toLocaleDateString()} · {formatTimeRange12(session.startTime, session.endTime)} · Day {session.eventDay?.dayNumber || '—'}</p></div><div className="flex shrink-0 items-center gap-4"><div className="hidden text-right text-xs sm:block"><p className="font-bold text-slate-900">{session.participants.length} learners</p><p className="mt-1 text-slate-400">{attendanceRate}% attendance</p></div><ChevronDownIcon className={`h-5 w-5 text-slate-400 transition ${open ? 'rotate-180' : ''}`} /></div></button>
    {open && <div className="border-t border-slate-100 bg-slate-50/50 p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-3"><Panel title="Approved learners" icon={UserGroupIcon}>{session.participants.length ? <ul className="space-y-2 text-sm text-slate-600">{session.participants.map((item) => <li key={item._id} className="rounded-lg bg-white px-3 py-2">{item.participant?.fullName}</li>)}</ul> : <Empty text="No approved learners yet." />}</Panel><Panel title="Participant feedback" icon={ChatBubbleLeftRightIcon}>{session.feedback.length ? <div className="space-y-2">{session.feedback.map((item) => <div key={item._id} className="rounded-lg bg-white p-3 text-sm"><p className="font-bold text-[#1a6b3c]">{item.trainerRating}/5 rating</p>{item.comments && <p className="mt-1 text-slate-600">{item.comments}</p>}</div>)}</div> : <Empty text="No feedback received yet." />}</Panel><Panel title="Learning materials" icon={DocumentTextIcon}><div className="space-y-2">{session.materials.map((item) => <div key={item._id} className="flex items-center justify-between gap-2 rounded-lg bg-white px-3 py-2 text-sm">{item.file?.path ? <button type="button" onClick={() => onDownload(item)} className="truncate text-left font-semibold text-[#1a6b3c] hover:underline">{item.title}</button> : <a href={item.url} target="_blank" rel="noreferrer" className="truncate font-semibold text-[#1a6b3c] hover:underline">{item.title}</a>}{session.status !== 'cancelled' && <button type="button" onClick={() => onRemove(session._id, item._id)} className="text-xs font-bold text-red-600">Delete</button>}</div>)}{!session.materials.length && <Empty text="No materials added yet." />}</div>{session.status !== 'cancelled' && <form onSubmit={(event) => onAdd(event, session._id)} className="mt-3 space-y-2"><input name="title" placeholder="e.g. Presentation slides" required className="w-full rounded-lg border border-black/10 bg-white p-2.5 text-sm" /><input name="url" type="url" placeholder="e.g. https://docs.google.com/..." required className="w-full rounded-lg border border-black/10 bg-white p-2.5 text-sm" /><button className="w-full rounded-lg bg-[#1a6b3c] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#124d2a]">Add link</button></form>}{session.status !== 'cancelled' && <form onSubmit={(event) => onUpload(event, session._id)} className="mt-3 space-y-2 border-t border-slate-200 pt-3"><p className="text-xs font-bold uppercase text-slate-500">Or upload a file</p><input name="title" placeholder="Label (optional — defaults to the file name)" className="w-full rounded-lg border border-black/10 bg-white p-2.5 text-sm" /><input name="file" type="file" required accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.txt,.zip" className="w-full rounded-lg border border-black/10 bg-white p-2 text-xs" /><button className="w-full rounded-lg border border-[#1a6b3c] px-4 py-2.5 text-sm font-bold text-[#1a6b3c] hover:bg-emerald-50">Upload file</button></form>}</Panel></div></div>}
  </article>;
}
*/
function DashboardSkeleton() { return <div className="space-y-6 animate-pulse"><div className="h-20 rounded-2xl bg-slate-200" /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-36 rounded-2xl bg-slate-200" />)}</div><div className="h-52 rounded-2xl bg-slate-200" /></div>; }


