import React, { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { ArrowDownTrayIcon, ArrowTopRightOnSquareIcon, CloudArrowUpIcon, DocumentTextIcon, LinkIcon, TrashIcon } from '@icons';
import api from '../../api/axios';
import ButtonSpinner from '../../components/common/ButtonSpinner';
import { MAX_MATERIAL_LABEL, materialSizeError } from '../../utils/uploadLimits';
import { formatTimeRange12 } from '../../utils/timeFormat';

export default function TrainerMaterials() {
  const [sessions, setSessions] = useState(null);
  const [eventId, setEventId] = useState('');
  const [dayId, setDayId] = useState('');
  const [sessionId, setSessionId] = useState('');
  const load = async () => { try { const response = await api.get('/trainer/dashboard'); setSessions(response.data.sessions || []); } catch (error) { toast.error(error.message || 'Unable to load learning materials.'); } };
  useEffect(() => { load(); }, []);

  const events = useMemo(() => uniqueBy((sessions || []).map((session) => session.event).filter(Boolean), '_id'), [sessions]);
  const days = useMemo(() => uniqueBy((sessions || []).filter((session) => entityId(session.event) === eventId).map((session) => session.eventDay).filter(Boolean), '_id').sort((a, b) => a.dayNumber - b.dayNumber), [sessions, eventId]);
  const availableSessions = useMemo(() => (sessions || []).filter((session) => entityId(session.event) === eventId && entityId(session.eventDay) === dayId), [sessions, eventId, dayId]);
  const selectedSession = availableSessions.find((session) => session._id === sessionId);

  useEffect(() => { if (events.length && !events.some((event) => event._id === eventId)) setEventId(events[0]._id); }, [events, eventId]);
  useEffect(() => { if (days.length && !days.some((day) => day._id === dayId)) setDayId(days[0]._id); }, [days, dayId]);
  useEffect(() => { if (availableSessions.length && !availableSessions.some((session) => session._id === sessionId)) setSessionId(availableSessions[0]._id); }, [availableSessions, sessionId]);

  const addLink = async (event, trainingId) => { event.preventDefault(); const form = event.currentTarget; const payload = new FormData(form); try { await api.post(`/trainer/trainings/${trainingId}/materials`, Object.fromEntries(payload)); form.reset(); await load(); toast.success('Link added.'); return true; } catch (error) { toast.error(error.message); return false; } };
  const uploadFile = async (event, trainingId) => { event.preventDefault(); const form = event.currentTarget; const body = new FormData(form); const file = body.get('file'); if (!file?.size) { toast.error('Choose a file to upload.'); return false; } const oversize = materialSizeError(file); if (oversize) { toast.error(oversize); return false; } try { await api.post(`/trainer/trainings/${trainingId}/materials/upload`, body, { headers: { 'Content-Type': 'multipart/form-data' } }); form.reset(); await load(); toast.success('File uploaded.'); return true; } catch (error) { toast.error(error.message); return false; } };
  const remove = async (trainingId, materialId) => { try { await api.delete(`/trainer/trainings/${trainingId}/materials/${materialId}`); await load(); toast.success('Material removed.'); } catch (error) { toast.error(error.message); } };
  const download = async (material) => { try { const response = await fetch(`/api/trainer/materials/${material._id}/download`, { headers: { Authorization: `Bearer ${localStorage.getItem('ntw_token')}` } }); if (!response.ok) throw new Error(); const url = window.URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = material.file?.originalName || material.title; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url); } catch { toast.error('Failed to download this file.'); } };

  if (!sessions) return <Skeleton />;
  return <div className="space-y-6"><PageHeader />{sessions.length ? <><MaterialFilters events={events} days={days} sessions={availableSessions} eventId={eventId} dayId={dayId} sessionId={sessionId} onEvent={(value) => { setEventId(value); setDayId(''); setSessionId(''); }} onDay={(value) => { setDayId(value); setSessionId(''); }} onSession={setSessionId} />{selectedSession ? <SessionMaterials session={selectedSession} onAdd={addLink} onUpload={uploadFile} onRemove={remove} onDownload={download} /> : <Empty title="Select a session" text="Choose an event, day, and session to manage its learning materials." />}</> : <Empty title="No assigned sessions" text="Your sessions will appear here after an administrator assigns you." />}</div>;
}

const entityId = (entity) => String(entity?._id || entity || '');
const uniqueBy = (items, key) => [...new Map(items.map((item) => [String(item[key]), item])).values()];

function MaterialFilters({ events, days, sessions, eventId, dayId, sessionId, onEvent, onDay, onSession }) { return <section aria-labelledby="material-filter-heading" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4"><h2 id="material-filter-heading" className="font-bold text-slate-950">Choose where to add materials</h2><p className="mt-1 text-xs text-slate-500">Select an event, then a day, and finally the training session.</p></div><div className="grid gap-3 md:grid-cols-3"><Select label="Event" value={eventId} onChange={onEvent} options={events.map((event) => ({ value: event._id, label: `${event.name}${event.year ? ` · ${event.year}` : ''}` }))} placeholder="Select event" /><Select label="Day" value={dayId} onChange={onDay} disabled={!eventId} options={days.map((day) => ({ value: day._id, label: `Day ${day.dayNumber} · ${day.theme}` }))} placeholder="Select day" /><Select label="Session" value={sessionId} onChange={onSession} disabled={!dayId} options={sessions.map((session) => ({ value: session._id, label: `${session.startTime} · ${session.title}` }))} placeholder="Select session" /></div></section>; }
function Select({ label, value, onChange, options, placeholder, disabled }) { return <label className="block text-xs font-bold text-slate-700">{label}<select value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800 outline-none focus:border-[#1a6b3c] focus:ring-2 focus:ring-emerald-100 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400"><option value="">{placeholder}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }

function PageHeader() { return <header><p className="text-xs font-bold uppercase tracking-[.16em] text-[#1a6b3c]">Resources</p><h1 className="mt-1 text-2xl font-black text-slate-950 sm:text-3xl">Learning materials</h1><p className="mt-2 text-sm text-slate-500">Upload files and share useful links for each training session.</p></header>; }
function SessionMaterials({ session, onAdd, onUpload, onRemove, onDownload }) { const editable = session.status !== 'cancelled'; return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-5 py-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase text-[#1a6b3c]">{session.status.replaceAll('_', ' ')}</span><span className="text-xs text-slate-400">{new Date(session.date).toLocaleDateString()} · {formatTimeRange12(session.startTime, session.endTime)}</span></div><h2 className="mt-2 font-bold text-slate-950">{session.title}</h2></header><div className="p-4 sm:p-5"><div className="space-y-2">{session.materials.map((item) => <Material key={item._id} item={item} editable={editable} download={onDownload} remove={() => onRemove(session._id, item._id)} />)}{!session.materials.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-center text-sm text-slate-400">No materials added yet.</p>}</div>{editable && <div className="mt-4 grid gap-3 lg:grid-cols-2"><LinkForm submit={(event) => onAdd(event, session._id)} /><UploadForm submit={(event) => onUpload(event, session._id)} /></div>}</div></article>; }
function Material({ item, editable, download, remove }) {
  const [downloading, setDownloading] = useState(false);
  const [removing, setRemoving] = useState(false);
  const busy = downloading || removing;
  const handleDownload = async () => { setDownloading(true); try { await download(item); } finally { setDownloading(false); } };
  const handleRemove = async () => { setRemoving(true); try { await remove(); } finally { setRemoving(false); } };
  return <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-emerald-50 text-[#1a6b3c]">{item.file?.path ? <DocumentTextIcon className="h-5 w-5" /> : <LinkIcon className="h-5 w-5" />}</span>{item.file?.path ? <button type="button" onClick={handleDownload} disabled={busy} className="min-w-0 text-left disabled:cursor-not-allowed disabled:opacity-60"><b className="block truncate text-sm">{item.title}</b><span className="flex items-center gap-1 text-xs text-slate-500">{downloading ? <ButtonSpinner size="xs" /> : <ArrowDownTrayIcon className="h-3.5 w-3.5" />} {downloading ? 'Downloading…' : 'Download'}</span></button> : <a href={item.url} target="_blank" rel="noreferrer" className="min-w-0"><b className="block truncate text-sm">{item.title}</b><span className="flex items-center gap-1 text-xs text-slate-500"><ArrowTopRightOnSquareIcon className="h-3.5 w-3.5" /> Open link</span></a>}</div>{editable && <button type="button" onClick={handleRemove} disabled={busy} aria-label={`Delete ${item.title}`} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600 disabled:cursor-not-allowed disabled:opacity-60">{removing ? <ButtonSpinner /> : <TrashIcon className="h-5 w-5" />}</button>}</div>;
}
function LinkForm({ submit }) {
  const [saving, setSaving] = useState(false);
  const handle = async (event) => { event.preventDefault(); setSaving(true); try { await submit(event); } finally { setSaving(false); } };
  return <form onSubmit={handle} className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-3"><Heading icon={LinkIcon} title="Add a link" text="Share an external resource" /><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1"><Field label="Title" name="title" placeholder="Presentation slides" required disabled={saving} /><Field label="URL" name="url" type="url" placeholder="https://docs.google.com/..." required disabled={saving} /></div><button disabled={saving} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#1a6b3c] px-4 text-sm font-bold text-white hover:bg-[#124d2a] disabled:cursor-not-allowed disabled:opacity-60">{saving && <ButtonSpinner />}{saving ? 'Adding…' : 'Add link'}</button></form>;
}
function UploadForm({ submit }) {
  const [name, setName] = useState('');
  const [oversize, setOversize] = useState('');
  const [uploading, setUploading] = useState(false);
  const pick = (event) => { const file = event.target.files?.[0]; setName(file?.name || ''); setOversize(materialSizeError(file)); };
  const handle = async (event) => { event.preventDefault(); setUploading(true); try { if (await submit(event)) { setName(''); setOversize(''); } } finally { setUploading(false); } };
  return <form onSubmit={handle} className="rounded-xl border border-slate-200 p-3"><Heading icon={CloudArrowUpIcon} title="Upload a file" text={`PDF, Office, text, or ZIP · up to ${MAX_MATERIAL_LABEL}`} /><Field label="Display name (optional)" name="title" placeholder="Defaults to file name" disabled={uploading} /><label className="mt-2 flex min-h-16 cursor-pointer items-center gap-3 rounded-xl border border-dashed border-emerald-300 bg-emerald-50/40 px-3 hover:bg-emerald-50 focus-within:ring-2 focus-within:ring-[#1a6b3c]"><input className="sr-only" name="file" type="file" required disabled={uploading} accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.txt,.zip" onChange={pick} /><CloudArrowUpIcon className="h-8 w-8 shrink-0 text-[#1a6b3c]" /><span className="min-w-0"><b className="block truncate text-sm">{name || 'Choose a file'}</b><span className="text-xs text-slate-500">Click to browse your device</span></span></label>{oversize && <p role="alert" className="mt-2 text-xs font-bold text-rose-600">{oversize}</p>}<button disabled={uploading || Boolean(oversize)} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#1a6b3c] text-sm font-bold text-[#1a6b3c] hover:bg-emerald-50 disabled:cursor-not-allowed disabled:opacity-60">{uploading && <ButtonSpinner />}{uploading ? 'Uploading…' : 'Upload selected file'}</button></form>;
}
function Heading({ icon: Icon, title, text }) { return <div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#1a6b3c] shadow-sm"><Icon className="h-5 w-5" /></span><div><h3 className="text-sm font-bold">{title}</h3><p className="text-xs text-slate-500">{text}</p></div></div>; }
function Field({ label, ...props }) { return <label className="block text-xs font-bold text-slate-700">{label}<input {...props} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-[#1a6b3c] focus:ring-2 focus:ring-emerald-100 disabled:cursor-not-allowed disabled:opacity-60" /></label>; }
function Empty({ title, text }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><DocumentTextIcon className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-3 font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>; }
function Skeleton() { return <div className="animate-pulse space-y-5"><div className="h-20 rounded-xl bg-slate-200" /><div className="h-80 rounded-2xl bg-slate-200" /></div>; }
